#!/bin/bash

log() {
  echo
  echo "###"
  echo $@
  echo "###"
  echo
}

log "Make Linux (x86_64) build"

mkdir -p build
cd build
rm -rf CMakeCache.txt CMakeFiles cmake_install.cmake konstructs Makefile

cmake ..
VERBOSE=1 make

log "Package a Linux build"

mkdir -p konstructs-client-linux && cd konstructs-client-linux
cp ../konstructs konstructs-client
cp -r ../../shaders ../../textures .
cd .. && tar cfj konstructs-client.tar.bz2 konstructs-client-linux
