#!/bin/bash -e
set -e

cd /build

if [[ $MAKE_DOCS == true ]]; then
  doxygen Doxyfile
else
  ./package/compile-linux
fi

if [[ $MAKE_DEB == true ]] || [[ $MAKE_RPM == true ]]; then
  ./package/make-packages
fi

if [[ $CROSS_COMPILE == true ]]; then
  ./package/cross-compile-windows
fi
