#!/bin/bash -e
set -e

cd /build

./package/compile-linux

if [[ $MAKE_DEB == true ]] || [[ $MAKE_RPM == true ]]; then
  ./package/make-packages
fi

if [[ $CROSS_COMPILE == true ]]; then
  ./package/cross-compile-windows
fi
