#!/bin/bash -e

if [[ true == $MAKE_DOCS ]]; then

  repo=$PWD
  rev=$(git rev-parse --short HEAD)

  mkdir ~/docs
  cd ~/docs
  git init
  git config user.name "Travis"
  git config user.email "travis@konstructs.org"
  git remote add origin "https://$GH_TOKEN@github.com/konstructs/client.git"
  git fetch origin
  git checkout gh-pages

  rsync -rv $repo/docs/html/ .

  git add -A .
  git commit -m "rebuild pages at ${rev}"
  git push origin gh-pages

fi
